INSERT INTO GENRE (NAME)
VALUES ('Комедия');
INSERT INTO GENRE (NAME)
VALUES ('Драма');
INSERT INTO GENRE (NAME)
VALUES ('Мультфильм');
INSERT INTO GENRE (NAME)
VALUES ('Триллер');
INSERT INTO GENRE (NAME)
VALUES ('Документальный');
INSERT INTO GENRE (NAME)
VALUES ('Боевик');
INSERT INTO RATING (NAME)
VALUES ('G');
INSERT INTO RATING (NAME)
VALUES ('PG');
INSERT INTO RATING (NAME)
VALUES ('PG-13');
INSERT INTO RATING (NAME)
VALUES ('R');
INSERT INTO RATING (NAME)
VALUES ('NC-17');